title: Academic Indigestion
# baseurl: "/digest"
baseurl: "/"
author: Alex Tung
email: atung323@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to let out my thoughts as I read papers, journal entries, textbooks, or things that I've scraped from around the web.
# social links
github_username: alextongue

show_excerpts: false # set to false to remove excerpts on the homepage

theme: "just-the-docs"
markdown: kramdown

search_enabled: true
search_tokenizer_separator: /[\s/]+/

favicon: https://github.com/alextongue/alextongue.github.io/blob/master/favicons/favicon_32.png?raw=true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

plugins:
  - jekyll-seo-tag

sass:
    sass_dir: _sass

footer_content: "Copyright &copy; 2019-2020 Alex Tung. Rescued by Grace. Licensed by <a href=\"https://github.com/alextongue/alextongue.github.io/blob/master/LICENSE\">MIT</a>. Styled with <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a>. Built with <a href=\"https://github.com/jekyll/jekyll\">Jekyll</a>."